### PR TITLE
TodoMVC example doesn't put selected class on footer buttons

### PR DESCRIPTION
**Pull request by deklanw**
(As far as I could tell)

I'm not sure if my way of implementing it is optimal, but it works. It was my time doing anything with Turbine, so I'm open to correction.

I could have probably kept the `filterItem` function but I think it's better being explicit in this case since it's only 3 buttons.

### CODE REVIEW

**Comment by paldepind** [comment]
> (As far as I could tell)

You're right.

Thee implementation looks great to me :+1:.

> I could have probably kept the `filterItem` function but I think it's better being explicit in this case since it's only 3 buttons.

I think you should put `filterItem` back in. I think it made things more clear, shorter, and demonstrated the practice of separating things into small components. If you'd update the PR with `filterItem` I'd love to merge this PR :smile:

**Comment by deklanw** [comment]
@paldepind 

Reinstated. But, I still think there's something wrong here. The typechecking is broken because of the string interpolation on the output. Seems like there should be a better way.

**Comment by paldepind** [comment]
@deklanw 

> But, I still think there's something wrong here. The typechecking is broken because of the string interpolation on the output. Seems like there should be a better way.

Yes, I agree. IMO the problem is that `filterItem` calls `output` on its own component. It's both confusing and not typesafe. I'll merge the PR as is (the problem was there before) and then I'll take a stab at fixing the problem.

**Comment by paldepind** [comment]
Thank a lot for the PR @deklanw. It's really nice to get this fixed :smile:

**Pull request merged**
